package adminapp.view;

import adminapp.dto.Inicializacion;
import adminapp.service.RenumeracionService;
import adminapp.service.ServicioService;
import adminapp.service.SuministroService;
import adminapp.service.TipoAbstract;
import java.text.DecimalFormat;

/**
 *
 * @author Luis Checa Alama
 */
public class AdminappView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminappView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        txtn4 = new javax.swing.JTextField();
        txtn5 = new javax.swing.JTextField();
        txtn6 = new javax.swing.JTextField();
        txtn7 = new javax.swing.JTextField();
        txtn8 = new javax.swing.JTextField();
        txtn9 = new javax.swing.JTextField();
        txtn10 = new javax.swing.JTextField();
        txtn11 = new javax.swing.JTextField();
        txttot1 = new javax.swing.JTextField();
        txttot2 = new javax.swing.JTextField();
        txttot3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txttotg = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUADRO DE GASTOS OPERATIVOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 51, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\t\tÁREA DE ADMINISTRACION\n\t \t     CUADRO DE GASTOS OPERATIVOS\n\t             Del 01/05/2016 al 30/06/2016");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Alquiler de sede administrativa(S7. 2500)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Luz (S/. 790)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Agua (S/. 660)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Teléfono (S/. 300)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, 590, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Papel (S/. 800)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tóner (S/. 985)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Otros Varios (S/.180)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 153, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setText("Pago mensual por Materiales de oficina");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 600, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 153, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setText("Pago Mensual de Servicios de oficinas administrativas");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Mensual :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 590, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 153, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setText("Pago por Renumeraciones mensuales");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 600, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Mensual :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Sueldo del Gerente   (S/. 10,200)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Sueldo de cada empleado de Sistemas  (S/. 2100 c/u) son 2 en total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Sueldo de cada empleado de Marketing (S/. 2400 c/u) son 3 en total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Sueldo de Secretarias (S/. 1,500 c/u ) son 2 en total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 326, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 590, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Total Mensual :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, -1, -1));

        txtn1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn1.setText("jTextField4");
        txtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn1KeyTyped(evt);
            }
        });
        getContentPane().add(txtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 99, -1));

        txtn2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn2.setText("jTextField5");
        txtn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn2KeyTyped(evt);
            }
        });
        getContentPane().add(txtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 99, -1));

        txtn3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn3.setText("jTextField6");
        txtn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn3KeyTyped(evt);
            }
        });
        getContentPane().add(txtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 99, -1));

        txtn4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn4.setText("jTextField7");
        txtn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn4KeyTyped(evt);
            }
        });
        getContentPane().add(txtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 99, -1));

        txtn5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn5.setText("jTextField8");
        txtn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn5KeyTyped(evt);
            }
        });
        getContentPane().add(txtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 104, -1));

        txtn6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn6.setText("jTextField9");
        txtn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn6KeyTyped(evt);
            }
        });
        getContentPane().add(txtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 104, -1));

        txtn7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn7.setText("jTextField10");
        txtn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn7KeyTyped(evt);
            }
        });
        getContentPane().add(txtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 104, -1));

        txtn8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn8.setText("jTextField11");
        txtn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn8KeyTyped(evt);
            }
        });
        getContentPane().add(txtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 99, -1));

        txtn9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn9.setText("jTextField12");
        txtn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn9KeyTyped(evt);
            }
        });
        getContentPane().add(txtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 99, -1));

        txtn10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn10.setText("jTextField13");
        txtn10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn10KeyTyped(evt);
            }
        });
        getContentPane().add(txtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 99, -1));

        txtn11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn11.setText("jTextField14");
        txtn11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn11KeyTyped(evt);
            }
        });
        getContentPane().add(txtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 99, -1));

        txttot1.setEditable(false);
        txttot1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttot1.setText("jTextField15");
        getContentPane().add(txttot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, -1));

        txttot2.setEditable(false);
        txttot2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttot2.setText("jTextField16");
        getContentPane().add(txttot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 100, 30));

        txttot3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttot3.setText("jTextField17");
        getContentPane().add(txttot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 100, -1));

        jTextField4.setBackground(new java.awt.Color(0, 153, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("      Total General  :      ");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 390, -1));

        txttotg.setEditable(false);
        txttotg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotg.setText("jTextField5");
        getContentPane().add(txttotg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 100, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, -1, -1));

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, -1, -1));

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        limpiar();
        habdes(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        limpiar();
        habdes(true);
        txtn1.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtn1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn1KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0' || c>'9') &&  (c != '.') ){
               evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn1KeyTyped

    private void txtn2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn2KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn2KeyTyped

    private void txtn3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn3KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn3KeyTyped

    private void txtn4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn4KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn4KeyTyped

    private void txtn5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn5KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn5KeyTyped

    private void txtn6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn6KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.')){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn6KeyTyped

    private void txtn7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn7KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn7KeyTyped

    private void txtn8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn8KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn8KeyTyped

    private void txtn9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn9KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn9KeyTyped

    private void txtn10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn10KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.')){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn10KeyTyped

    private void txtn11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn11KeyTyped
        char c=evt.getKeyChar();
        if ((c<'0'|| c>'9') &&  (c != '.') ){
            evt.consume();  //cancela la tecla pulsada
        }        
    }//GEN-LAST:event_txtn11KeyTyped

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        //datos
           double n1= Double.parseDouble(txtn1.getText());
           double n2= Double.parseDouble(txtn2.getText());
           double n3= Double.parseDouble(txtn3.getText());
           double n4= Double.parseDouble(txtn4.getText());
           double n5= Double.parseDouble(txtn5.getText());
           double n6= Double.parseDouble(txtn6.getText());
           double n7= Double.parseDouble(txtn7.getText());
           double n8= Double.parseDouble(txtn8.getText());
           double n9= Double.parseDouble(txtn9.getText());
           double n10= Double.parseDouble(txtn10.getText());
           double n11= Double.parseDouble(txtn11.getText());
        // proceso
     
        //creando el objeto
        DecimalFormat formateo =new DecimalFormat("#####.##");

        Inicializacion dto = new Inicializacion();
        
        //proceso 
          TipoAbstract tipo1 = new ServicioService();
          dto.setTotal1(tipo1.calcular(n1,n2,n3,n4));

          TipoAbstract tipo2 = new SuministroService();        
          dto.setTotal2(tipo2.calcular(n5,n6,n7, 0.0));

          TipoAbstract tipo3 = new RenumeracionService();
          dto.setTotal3(tipo3.calcular(n8,n9,n10,n11));
        
          dto.setTottalg(dto.getTotal1()+dto.getTotal2()+dto.getTotal3() );
        
        //salida
        
        txttot1.setText(String.valueOf(formateo.format(dto.getTotal1())));
        txttot2.setText(String.valueOf(formateo.format(dto.getTotal2())));
        txttot3.setText(String.valueOf(formateo.format(dto.getTotal3())));        
        txttotg.setText(String.valueOf(formateo.format(dto.getTottalg())));
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminappView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminappView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminappView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminappView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminappView().setVisible(true);
            }
        });
    }

    public void limpiar(){
        txtn1.setText(null);
        txtn2.setText(null);
        txtn3.setText(null);
        txtn4.setText(null);
        txtn5.setText(null);
        txtn6.setText(null);
        txtn7.setText(null);
        txtn8.setText(null);
        txtn9.setText(null);
        txtn10.setText(null);
        txtn11.setText(null);
        txttot1.setText(null);
        txttot2.setText(null);
        txttot3.setText(null);                
        txttotg.setText(null);
    }

    public void habdes(boolean sw){
        txtn1.setEnabled(sw);
        txtn2.setEnabled(sw);
        txtn3.setEnabled(sw);
        txtn4.setEnabled(sw);
        txtn5.setEnabled(sw);
        txtn6.setEnabled(sw);
        txtn7.setEnabled(sw);
        txtn8.setEnabled(sw);
        txtn9.setEnabled(sw);
        txtn10.setEnabled(sw);
        txtn11.setEnabled(sw);
        txttot1.setEnabled(sw);
        txttot2.setEnabled(sw);
        txttot3.setEnabled(sw);                
        txttotg.setEnabled(sw);        
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn10;
    private javax.swing.JTextField txtn11;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    private javax.swing.JTextField txtn4;
    private javax.swing.JTextField txtn5;
    private javax.swing.JTextField txtn6;
    private javax.swing.JTextField txtn7;
    private javax.swing.JTextField txtn8;
    private javax.swing.JTextField txtn9;
    private javax.swing.JTextField txttot1;
    private javax.swing.JTextField txttot2;
    private javax.swing.JTextField txttot3;
    private javax.swing.JTextField txttotg;
    // End of variables declaration//GEN-END:variables
}
