/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Datos.Personaje;
import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Aron
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
    ImageIcon iconorco = new ImageIcon(getClass().getResource("/resource/orco.png"));
     lblpj1.setIcon(iconorco);
     lblpj2.setIcon(iconorco);
     btnatacar1.setVisible(false);
       btnatacar2.setVisible(false);
       btnelegir2.setEnabled(false);
       txacombate1.setEnabled(false);
       txacombate2.setEnabled(false);
       btnelegir2.setVisible(false);
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lbltitulo = new javax.swing.JLabel();
        cmbpj1 = new javax.swing.JComboBox();
        cmbpj2 = new javax.swing.JComboBox();
        lblmensaje1 = new javax.swing.JLabel();
        lblmensaje2 = new javax.swing.JLabel();
        btnatacar1 = new javax.swing.JButton();
        btnatacar2 = new javax.swing.JButton();
        lblpj2 = new javax.swing.JLabel();
        lblpj1 = new javax.swing.JLabel();
        btnelegir = new javax.swing.JButton();
        btnelegir2 = new javax.swing.JButton();
        lblnombre1 = new javax.swing.JLabel();
        lblnombre2 = new javax.swing.JLabel();
        lblvs = new javax.swing.JLabel();
        lblpelea1 = new javax.swing.JLabel();
        lblpelea2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txacombate1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txacombate2 = new javax.swing.JTextArea();
        btnsalir = new javax.swing.JButton();
        lblwl1 = new javax.swing.JLabel();
        lblwl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP DE LUCHA POR TURNOS\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltitulo.setText("Batallas");
        getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 158, 48));

        cmbpj1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Orco", "Paladin", "Mago", "Elfo" }));
        cmbpj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpj1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbpj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        cmbpj2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Orco", "Paladin", "Mago", "Elfo" }));
        cmbpj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpj2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbpj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        lblmensaje1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmensaje1.setText("Elija un personaje :");
        getContentPane().add(lblmensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        lblmensaje2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmensaje2.setText("Elija un personaje :");
        getContentPane().add(lblmensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        btnatacar1.setText("Atacar");
        btnatacar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatacar1MouseClicked(evt);
            }
        });
        btnatacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatacar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnatacar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        btnatacar2.setText("Atacar");
        btnatacar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatacar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatacar2MouseClicked(evt);
            }
        });
        btnatacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatacar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnatacar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));
        getContentPane().add(lblpj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 150, 236));
        getContentPane().add(lblpj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 236));

        btnelegir.setText("Elegir");
        btnelegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnelegirMouseClicked(evt);
            }
        });
        btnelegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnelegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        btnelegir2.setText("Elegir");
        btnelegir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnelegir2MouseClicked(evt);
            }
        });
        getContentPane().add(btnelegir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        lblnombre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(lblnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, 20));

        lblnombre2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(lblnombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 48, 20));

        lblvs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblvs.setText("VS");
        getContentPane().add(lblvs, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 115, -1, -1));

        lblpelea1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpelea1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblpelea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 114));

        lblpelea2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpelea2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblpelea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 160, 110));

        txacombate1.setColumns(20);
        txacombate1.setRows(5);
        txacombate1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txacombate1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, 270));

        txacombate2.setColumns(20);
        txacombate2.setRows(5);
        txacombate2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(txacombate2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 130, 270));

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        lblwl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblwl1.setForeground(new java.awt.Color(255, 255, 255));
        lblwl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblwl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 120, 40));

        lblwl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblwl2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblwl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/pd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbpj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpj1ActionPerformed
    ImageIcon iconorco = new ImageIcon(getClass().getResource("/resource/orco.png"));
    ImageIcon iconpaladin = new ImageIcon(getClass().getResource("/resource/paladin.png"));
    ImageIcon iconmago = new ImageIcon(getClass().getResource("/resource/mago.png"));
    ImageIcon iconelfo = new ImageIcon(getClass().getResource("/resource/elfo.png"));
    String pj=(String) cmbpj1.getSelectedItem();
    
        if(pj.compareTo("Orco")==0)
        {lblpj1.setIcon(iconorco);}
         if(pj.compareTo("Paladin")==0)
        {lblpj1.setIcon(iconpaladin);}
          if(pj.compareTo("Mago")==0)
        {lblpj1.setIcon((iconmago));}
        if(pj.compareTo("Elfo")==0)
              lblpj1.setIcon((Icon) iconelfo);
          
        
    }//GEN-LAST:event_cmbpj1ActionPerformed

    private void cmbpj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpj2ActionPerformed
    ImageIcon iconorco = new ImageIcon(getClass().getResource("/resource/orco.png"));
    ImageIcon iconpaladin = new ImageIcon(getClass().getResource("/resource/paladin.png"));
    ImageIcon iconmago = new ImageIcon(getClass().getResource("/resource/mago.png"));
    ImageIcon iconelfo = new ImageIcon(getClass().getResource("/resource/elfo.png"));
    String pj=(String) cmbpj2.getSelectedItem();
    
        if(pj.compareTo("Orco")==0)
        {lblpj2.setIcon(iconorco);}
         if(pj.compareTo("Paladin")==0)
        {lblpj2.setIcon(iconpaladin);}
          if(pj.compareTo("Mago")==0)
        {lblpj2.setIcon((iconmago));}
        if(pj.compareTo("Elfo")==0)
              lblpj2.setIcon((Icon) iconelfo);
    }//GEN-LAST:event_cmbpj2ActionPerformed

    private void btnelegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelegirActionPerformed
    btnelegir2.setVisible(true);
    }//GEN-LAST:event_btnelegirActionPerformed



    private void btnelegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnelegirMouseClicked
        String pj=(String) cmbpj1.getSelectedItem();
        lblmensaje1.setVisible(false);
        cmbpj1.setVisible(false);
        
        btnelegir.setEnabled(false);
        lblnombre1.setText(pj);
        btnelegir2.setEnabled(true);
        lblpelea1.setText("A LUCHAR");
        
        
        
    }//GEN-LAST:event_btnelegirMouseClicked

    private void btnelegir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnelegir2MouseClicked
        String pj=(String) cmbpj2.getSelectedItem();
        cmbpj2.setVisible(false);
        btnelegir2.setEnabled(false);
        lblnombre2.setText(pj);
        btnatacar1.setVisible(true);
        btnatacar2.setVisible(true);
         btnelegir.setVisible(false);
         btnelegir2.setVisible(false);
         lblmensaje2.setVisible(false);
         lblpelea2.setText("A LUCHAR");
       ;
        
    }//GEN-LAST:event_btnelegir2MouseClicked
Personaje orco = new Personaje("Orco",100,2,5,2,1);
       Personaje orco2 = new Personaje("Orco",100,2,5,2,1);
       Personaje paladin = new Personaje("Paladin",90,3,4,4,2);
       Personaje paladin2 = new Personaje("Paladin",90,3,4,4,2);
       Personaje mago = new Personaje("Mago",80,5,3,3,5);
       Personaje mago2 = new Personaje("Mago",80,5,3,3,5);
       Personaje elfo = new Personaje("Elfo",80,3,3,5,3);
       Personaje elfo2 = new Personaje("Elfo",80,3,3,5,3);

    private void btnatacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatacar1ActionPerformed
       String pj=(String) cmbpj1.getSelectedItem();
       String pj2=(String) cmbpj2.getSelectedItem();
       lblpelea1.setVisible(false);
       lblpelea2.setVisible(false);
       
       
       int vida=0;
        if(pj.equals("Orco")&&(pj2.equals("Orco")))
        { vida = orco.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+orco.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+orco2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            orco2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+orco2.getVida()+" de vida");
            
        }
         if((orco.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Orco")&&(pj2.equals("Paladin")))
                
        { vida = orco.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+orco.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            paladin.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+paladin.getVida()+" de vida");
            if((orco.getVida()<=0) || (paladin.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
        } 
            if(pj.equals("Orco")&&(pj2.equals("Mago")))
        { vida = orco.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+orco.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+mago.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            mago.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+mago.getVida()+" de vida");
            
        }
            if((orco.getVida()<=0) || (mago.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Orco")&&(pj2.equals("Elfo")))
        { vida = orco.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+orco.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+mago.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            elfo.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+elfo.getVida()+" de vida");
            
        }
            if((orco.getVida()<=0) || (elfo.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Paladin")&&(pj2.equals("Orco")))
        { vida = paladin.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+paladin.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+orco2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            orco2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+orco2.getVida()+" de vida");
        }
            if((paladin.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Paladin")&&(pj2.equals("Paladin")))
        { vida = paladin.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+paladin.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+paladin2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            paladin2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+paladin2.getVida()+" de vida");
        }
            if((paladin.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Paladin")&&(pj2.equals("Mago")))
        { vida = paladin.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+paladin.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+mago2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            mago2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+mago2.getVida()+" de vida");
        }
             if((paladin.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            
            if(pj.equals("Paladin")&&(pj2.equals("Elfo")))
        { vida = paladin.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+paladin.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+elfo2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            elfo2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+elfo2.getVida()+" de vida");
        }
             if((paladin.getVida()<=0) || (elfo.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Mago")&&(pj2.equals("Orco")))
        { vida = mago.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+mago.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+orco2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            orco2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+orco2.getVida()+" de vida");
        }
             if((mago.getVida()<=0) || (orco.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
              if(pj.equals("Mago")&&(pj2.equals("Paladin")))
        { vida = mago.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+mago.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+paladin2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            paladin2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+paladin2.getVida()+" de vida");
        }
               if((mago.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
              if(pj.equals("Mago")&&(pj2.equals("Mago")))
        { vida = mago.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+mago.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+mago2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            mago2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+mago2.getVida()+" de vida");
        }
               if((mago.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
                if(pj.equals("Mago")&&(pj2.equals("Elfo")))
        { vida = mago.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+mago.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+elfo2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            elfo2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+elfo2.getVida()+" de vida");
        }
                 if((mago.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
           if(pj.equals("Elfo")&&(pj2.equals("Orco")))
        { vida = elfo.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+elfo.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+orco2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            orco2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+orco2.getVida()+" de vida");
        }
            if((elfo.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
          if(pj.equals("Elfo")&&(pj2.equals("Paladin")))
        { vida = elfo.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+elfo.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+paladin2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            paladin2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+paladin2.getVida()+" de vida");
        }
           if((elfo.getVida()<=0) || (paladin.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Elfo")&&(pj2.equals("Mago")))
        { vida = elfo.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+elfo.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+mago2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            mago2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+mago2.getVida()+" de vida");
        }
             if((elfo.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin2.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Elfo")&&(pj2.equals("Elfo")))
        { vida = elfo.dañoAtaque(pj);
        
            txacombate1.setText("tiene "+elfo.getVida()+"de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate2.setText("Tiene "+elfo2.getVida()+" de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"recibio "+vida+"de daño");
            elfo2.dañoRecibido(vida);
            txacombate2.setText(txacombate2.getText()+"\n"+"tiene "+elfo2.getVida()+" de vida");
        }
             if((elfo.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
    
           
    }//GEN-LAST:event_btnatacar1ActionPerformed

    private void btnatacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatacar2ActionPerformed
      String pj=(String) cmbpj1.getSelectedItem();
       String pj2=(String) cmbpj2.getSelectedItem();
       
       
       int vida=0;
        if(pj.equals("Orco")&&(pj2.equals("Orco")))
        { vida = orco2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+orco2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+orco.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            orco.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+orco.getVida()+" de vida");
            
             }
        if((orco.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Orco")&&(pj2.equals("Paladin")))
        if((orco.getVida()<=0) || (orco2.getVida()<=0))
        { btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
          
        if(pj.equals("Orco")&&(pj2.equals("Paladin")))
                
        { vida = paladin2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+paladin2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            orco.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+orco.getVida()+" de vida");
        } 
        if((orco.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Orco")&&(pj2.equals("Mago")))
        { vida = mago2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+mago2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+orco.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            orco.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+orco.getVida()+" de vida");
            
        }
             if((orco.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Orco")&&(pj2.equals("Elfo")))
        { vida = elfo2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+elfo2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+mago.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            orco.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+orco.getVida()+" de vida");
            
           
        }
            
            if((orco.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(orco.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Paladin")&&(pj2.equals("Orco")))
        { vida = orco2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+orco2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            paladin.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+paladin.getVida()+" de vida");
             if((paladin.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
        }
            if(pj.equals("Paladin")&&(pj2.equals("Paladin")))
        { vida = paladin2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+paladin2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            paladin.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+paladin.getVida()+" de vida");
           
        }
            if((paladin.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            } 
            
            if(pj.equals("Paladin")&&(pj2.equals("Mago")))
        { vida = mago2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+mago2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            paladin.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+paladin.getVida()+" de vida");
             if((paladin.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            
        }
            
            if(pj.equals("Paladin")&&(pj2.equals("Elfo")))
        { vida = elfo2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+elfo2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+paladin.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            paladin.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+paladin.getVida()+" de vida");
        }
             if((paladin.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(paladin.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Mago")&&(pj2.equals("Orco")))
        { vida = orco2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+orco2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+mago.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            mago.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+mago.getVida()+" de vida");
        }
             if((mago.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
              if(pj.equals("Mago")&&(pj2.equals("Paladin")))
        { vida = paladin2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+paladin2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+mago.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            mago.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+mago.getVida()+" de vida");
        }
               if((mago.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
              if(pj.equals("Mago")&&(pj2.equals("Mago")))
        { vida = mago2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+mago2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+mago.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            mago.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+mago.getVida()+" de vida");
        }
               if((mago.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
              
              
                if(pj.equals("Mago")&&(pj2.equals("Elfo")))
        { vida = elfo2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+elfo2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+mago.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            mago.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+mago.getVida()+" de vida");
        }
                 if((mago.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(mago.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
           if(pj.equals("Elfo")&&(pj2.equals("Orco")))
        { vida = orco2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+orco2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+elfo.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            elfo.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+elfo.getVida()+" de vida");
        }
            if((elfo.getVida()<=0) || (orco2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(orco2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
          if(pj.equals("Elfo")&&(pj2.equals("Paladin")))
        { vida = paladin2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+paladin2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+elfo.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            elfo.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+elfo.getVida()+" de vida");
        }
           if((elfo.getVida()<=0) || (paladin2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(paladin2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Elfo")&&(pj2.equals("Mago")))
        { vida = mago.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+mago.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+elfo.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            elfo.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+elfo.getVida()+" de vida");
        }
             if((elfo.getVida()<=0) || (mago2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(mago2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
            if(pj.equals("Elfo")&&(pj2.equals("Elfo")))
        { vida = elfo2.dañoAtaque(pj);
        
            txacombate2.setText("tiene "+elfo2.getVida()+"de vida");
            txacombate2.setText(txacombate2.getText()+"\n"+"hizo "+vida+" de daño");
            
            txacombate1.setText("Tiene "+elfo.getVida()+" de vida");
            txacombate1.setText(txacombate1.getText()+"\n"+"recibio "+vida+"de daño");
            elfo.dañoRecibido(vida);
            txacombate1.setText(txacombate1.getText()+"\n"+"tiene "+elfo.getVida()+" de vida");
        }
             if((elfo.getVida()<=0) || (elfo2.getVida()<=0))
         {  btnatacar1.setVisible(false);
            btnatacar2.setVisible(false);}
            
            
            if(elfo.getVida()<=0)
            { lblwl1.setText("PERDEDOR");
            lblwl2.setText("VENCEDOR");}
             if(elfo2.getVida()<=0)
            {  lblwl1.setText("GANADOR");
               lblwl2.setText("VENCEDOR");
            }
        
        
        
    }//GEN-LAST:event_btnatacar2ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnatacar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacar1MouseClicked
        this.btnatacar1.setEnabled(false);
        this.btnatacar2.setVisible(true);
        this.btnatacar2.setEnabled(true);
    }//GEN-LAST:event_btnatacar1MouseClicked

    private void btnatacar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacar2MouseClicked
       this.btnatacar2.setEnabled(false);
       this.btnatacar1.setEnabled(true);
    }//GEN-LAST:event_btnatacar2MouseClicked

  
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatacar1;
    private javax.swing.JButton btnatacar2;
    private javax.swing.JButton btnelegir;
    private javax.swing.JButton btnelegir2;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox cmbpj1;
    private javax.swing.JComboBox cmbpj2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblmensaje1;
    private javax.swing.JLabel lblmensaje2;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JLabel lblnombre2;
    private javax.swing.JLabel lblpelea1;
    private javax.swing.JLabel lblpelea2;
    private javax.swing.JLabel lblpj1;
    private javax.swing.JLabel lblpj2;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblvs;
    private javax.swing.JLabel lblwl1;
    private javax.swing.JLabel lblwl2;
    private javax.swing.JTextArea txacombate1;
    private javax.swing.JTextArea txacombate2;
    // End of variables declaration//GEN-END:variables
}
